apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ktswebapprs
spec:
  replicas: 2
  selector:
   matchLabels:
     app: ktswebapp
  template:
    metadata:
      name: ktswebapp
      labels:
        app: ktswebapp
    spec:
      containers:
        - name: ktswebapp
          image: lokeshsdockerhub/kts-web-app:1
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 250Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ktswebappsvc
spec:
  type: NodePort
  selector:
    app: ktswebapp
  ports:
    - port: 80
      targetPort: 8080
