apiVersion: v1
kind: ReplicationController
metadata:
   name: pythonapprc
   namespace: test-ns
spec:
  replicas: 2
  selector:
    app: pythonapp
  template:
    metadata:
      name: pythonapp
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: lokeshsdockerhub/pythonapp:2
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 350m
            memory: 256Mi
        ports:
         - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
   name: pythonappsvc
   namespace: test-ns
spec:
  type: NodePort
  selector:
    app: pythonapp
  ports:
    - port: 80
      targetPort: 5000
