#Complete Manifest Where in single yml we defined Deployment & Service for SpringApp ,configMap&Secret ,PVC(with default  StorageClass)
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 650Mi
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongoconfigmap
                key: mongodbusername
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongosecret
                key: mongodbpassword
          volumeMounts:
          - mountPath: /data/db
            name: mongovol
      volumes:
        - name: mongovol
          persistentVolumeClaim:
            claimName: mongopvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
  namespace: test-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
#Springboot application deployment in k8s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: lokeshsdockerhub/springboot:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 256m
              memory: 300Mi
            limits:
              cpu: 350m
              memory: 516Mi
          env:
           - name: MONGO_DB_HOSTNAME
             value: mongosvc
           - name: MONGO_DB_USERNAME
             valueFrom:
               configMapKeyRef:
                 name: mongoconfigmap
                 key: mongodbusername
           - name: MONGO_DB_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mongosecret
                 key: mongodbpassword
---
apiVersion: v1
kind: Service
metadata:
  name: springappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
 
